name = "mugunghwa"
main = "build/index.js"
compatibility_date = "2025-10-08"

[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]
name = ""
github_key = ""
api_key = ""
db_name = ""

[[d1_databases]]
binding = ""
database_name = ""
database_id = ""